### ISSUE TITLE
all animals / all locations is not working

### ISSUE THREAD

**Issue by alexramos1** [alexramos1/shelterbuddy-api-accelerator#2]
the ALL/ALL combination causes a 500 error.
From MP,

> I agree that getting the “All” option available for both the animals and the locations should be first priority. This will open up the options to set up a post call filter for a single animal ID or name. It would be more ideal, in my opinion, to have an endpoint that can be queried, but this may take longer to do. I think I can set up a post search filter relatively cleanly, since I’m already filtering for age and gender.

**Comment by alexramos1** [comment]
From MP, 

> I agree that getting the “All” option available for both the animals and the locations should be first priority. This will open up the options to set up a post call filter for a single animal ID or name. It would be more ideal, in my opinion, to have an endpoint that can be queried, but this may take longer to do. I think I can set up a post search filter relatively cleanly, since I’m already filtering for age and gender.

**Comment by Blackbaud-MariPool** [comment]
I think getting this resolved would be helpful for ux, and buy us more time to see if we can set up endpoints for multi-location and multi-animal searches by implementing filters.

**Comment by alexramos1** [comment]
Could Not Reproduce // this is actually working fine in the current production endpoint. There was probably something wrong with the test configuration.
